name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false

      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build NixOS with kernel v6.6 (cross-compiled)
        run: nix build .#nixosImage -L --print-build-logs

      - name: Stage NixOS with kernel v6.6 for release
        run: cp result/*.img.xz .

      - name: Build Bootchain image (cross-compiled)
        run: nix build .#bootchain -L --print-build-logs

      - name: Stage bootchain for release
        run: cp result/bootloader_ddr5_secboot.bin bootloader_ddr5_secboot.bin

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          files: |
            *.img.xz
            bootloader_ddr5_secboot.bin
